from __future__ import annotations

from .models import WorkflowTemplate

WORKFLOW_TEMPLATES: tuple[WorkflowTemplate, ...] = (
    WorkflowTemplate(
        id="career_interview_prep",
        title="Career and Interview Prep",
        description="Turn recruiting, internship, and interview threads into a follow-up plan.",
        keywords=("实习", "面试", "简历", "校招", "投递", "offer", "招聘", "求职"),
        tools=("search", "docs", "email", "calendar"),
        inputs=("target role", "deadline", "materials", "follow-up status"),
        outputs=("application checklist", "follow-up draft", "interview prep brief"),
        steps=(
            "Extract the role, company, deadline, and missing material from the thread.",
            "Check whether the resume, cover letter, and follow-up note are ready.",
            "Draft the next action and a concise reply.",
            "Log the next reminder and owner.",
        ),
        evaluation=(
            "Deadline is explicit.",
            "Missing fields are identified.",
            "Next action is concrete.",
            "Tone stays concise and professional.",
        ),
        model_fit=("OpenAI", "Anthropic", "DeepSeek", "Kimi"),
    ),
    WorkflowTemplate(
        id="academic_workflow",
        title="Academic Workflows",
        description="Turn homework, papers, and exams into a structured study or submission plan.",
        keywords=("作业", "论文", "课程", "考试", "表格", "答辩", "学分", "报告"),
        tools=("docs", "spreadsheet", "search"),
        inputs=("assignment brief", "deadline", "rubric", "source list"),
        outputs=("outline", "submission checklist", "source tracker"),
        steps=(
            "Extract the assignment type, deadline, and required deliverables.",
            "Draft the outline and identify missing references or data.",
            "Break the task into a daily plan.",
            "Record the final submission checklist.",
        ),
        evaluation=(
            "Structure is complete.",
            "References are tracked.",
            "Deadline is visible.",
            "The output is easy to hand off.",
        ),
        model_fit=("OpenAI", "Anthropic", "DeepSeek", "Kimi"),
    ),
    WorkflowTemplate(
        id="project_startup_ops",
        title="Project and Startup Ops",
        description="Turn project, product, and startup chats into a decision log and next-step plan.",
        keywords=("项目", "创业", "合伙", "会议", "产品", "需求", "方案", "demo", "迭代"),
        tools=("docs", "whiteboard", "calendar", "search"),
        inputs=("problem statement", "stakeholders", "deadline", "open questions"),
        outputs=("project brief", "meeting agenda", "decision log"),
        steps=(
            "Extract the problem statement and stakeholders.",
            "List open questions, blockers, and decisions needed.",
            "Draft an agenda or planning brief.",
            "Convert the thread into a next-step checklist.",
        ),
        evaluation=(
            "Stakeholders are mapped.",
            "Next step is assigned.",
            "Risks are named.",
            "The workflow can be reused.",
        ),
        model_fit=("OpenAI", "Anthropic", "DeepSeek", "Kimi"),
    ),
    WorkflowTemplate(
        id="content_distribution",
        title="Content and Distribution Ops",
        description="Turn short-video, social, and copywriting threads into a publishable content brief.",
        keywords=("小红书", "抖音", "公众号", "文案", "视频", "PPT", "海报", "运营", "短视频"),
        tools=("browser", "docs", "image", "spreadsheet"),
        inputs=("platform", "audience", "hook", "CTA"),
        outputs=("content brief", "hook list", "distribution plan"),
        steps=(
            "Identify the platform, audience, and content objective.",
            "Extract the hook, angle, and call to action.",
            "Draft a distribution checklist and repurposing plan.",
            "Capture the next review milestone.",
        ),
        evaluation=(
            "Platform fit is clear.",
            "Hook is sharp.",
            "CTA is present.",
            "The plan can be executed repeatedly.",
        ),
        model_fit=("OpenAI", "Anthropic", "DeepSeek", "Kimi"),
    ),
    WorkflowTemplate(
        id="finance_research",
        title="Finance and Research",
        description="Turn investment and research chats into a structured memo and risk checklist.",
        keywords=("投资", "基金", "股票", "理财", "证券", "定投", "收益"),
        tools=("search", "spreadsheet", "docs"),
        inputs=("thesis", "tickers", "time horizon", "risk tolerance"),
        outputs=("research memo", "risk checklist", "watchlist"),
        steps=(
            "Extract the thesis, tickers, and time horizon.",
            "List assumptions, risks, and sources.",
            "Draft a concise memo and watchlist.",
            "Add a follow-up review date.",
        ),
        evaluation=(
            "Sources are named.",
            "Risk is disclosed.",
            "Assumptions are explicit.",
            "The memo is easy to revisit.",
        ),
        model_fit=("OpenAI", "Anthropic", "DeepSeek", "Kimi"),
    ),
    WorkflowTemplate(
        id="coordination_ops",
        title="Coordination and Handoff",
        description="Turn casual help requests, file sharing, and status updates into a clean handoff.",
        keywords=("帮忙", "资料", "整理", "汇总", "表格", "发给", "共享"),
        tools=("docs", "spreadsheet", "email", "calendar"),
        inputs=("request", "owner", "deadline", "current status"),
        outputs=("task list", "handoff note", "status update"),
        steps=(
            "Identify the request, the owner, and the deadline.",
            "Summarize the needed files or data.",
            "Draft the handoff note or follow-up message.",
            "Log the status and the next check-in.",
        ),
        evaluation=(
            "Owner is clear.",
            "Due date is clear.",
            "The format is reusable.",
            "Nothing essential is left implicit.",
        ),
        model_fit=("OpenAI", "Anthropic", "DeepSeek", "Kimi"),
    ),
)

